### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by timholy** [JuliaCollections/OrderedCollections.jl#1]
I'm not sure which Appveyor account is used for running tests in JuliaCollections. I can add this repo to my personal account, but if there's a better one would someone please activate it?

**Comment by kmsquire** [comment]
Appveyor for DataStructures.jl is running under my personal account.  I had looked into using the JuliaLang account at one point, and was told (I believe by @tkelman) that they didn't want too many things running there (it does tend to get backed up), and that running under personal accounts is fine.

AFAIK, there is no JuliaCollections appveyor account--Appveyor does not seem to have a notion of (free) organizational accounts for open source projects.

**Comment by timholy** [comment]
If you wouldn't mind turning it on for OrderedCollections too, that would be great!

**Comment by kmsquire** [comment]
Done!

https://ci.appveyor.com/project/kmsquire/orderedcollections-jl
