### ISSUE TITLE
Type piracy causing warnings

### ISSUE THREAD

**Issue by rdeits** [JuliaCollections/OrderedCollections.jl#10]
This package and DataStructures both commit some type-piracy by trying to define `sort(::Dict)`. That used to silently work OK, but now it results in warnings when both packages are loaded, since the pirated definitions get overloaded by whatever package is loaded second. 

Maybe OrderedCollections should not define that `sort` method?

**Comment by rdeits** [comment]
Ah, it looks like that definition was just moved into this package, so is the plan to delete it from DataStructures.jl ?

**Comment by timholy** [comment]
Yes, it's just not merged yet. See https://github.com/JuliaCollections/DataStructures.jl/pull/448

**Comment by tlnagy** [comment]
Yeah, this is dumping errors out everywhere for me. Would be great to have this fixed soon. Thanks!

**Comment by timholy** [comment]
It's been merged and tagged, just waiting for METADATA. Sorry for the inconvenience; I don't think there's a way for our current package manager to fix this by doing both updates simultaneously, at least not without modifying the .travis.yml script to install a particular branch.
