### ISSUE TITLE
Document that `keys` maintains order.

### ISSUE THREAD

**Issue by matthieugomez** [JuliaCollections/OrderedCollections.jl#13]
Is there a way to iterate on the keys of an OrderedDict in order? It seems that `keys()` returns a `Keyset`, and I am not sure whether it keeps the order or not.
```julia
julia> y = OrderedDict(:a =>1, :b => 2)
OrderedDict{Symbol,Int64} with 2 entries:
  :a => 1
  :b => 2

julia> keys(y)
Base.KeySet for a OrderedDict{Symbol,Int64} with 2 entries. Keys:
  :a
  :b
```

**Comment by oxinabox** [comment]
Order *is* maintained by a `KeySet`.

At least according to my 10_000 key long test.

```
julia> using Random

julia> keys_orig = [Random.randstring(5) for _ in 1:10_000];

julia> od = OrderedDict(Pair.(keys_orig, 1));

julia> keys_orig == collect(keys(od))
true
```

I suggest when filing an issue include a Minimum Verifyable Example of the bug you are encountering.
Rather than an example which demonstrates the bug **not** occurring.

**Comment by matthieugomez** [comment]
My point is that nothing in the documentation says that `keys` maintains the order, so there is no way to be 100% sure. The documentation only mentions that the order is maintained for iterations (i.e. `for d in OrderedDict(:a =>1, :b => 2)`)
