### ISSUE TITLE
Make OrderedSet a subtype of Base.AbstractSet

### ISSUE THREAD

**Issue by simonschoelly** [JuliaCollections/OrderedCollections.jl#15]
The code for `OrderedSet` containts the following comment
>  TODO: Most of these functions should be removed once AbstractSet is introduced there
>  (see https://github.com/JuliaLang/julia/issues/5533)

`Base.AbstractSet` exists now, so should I make it a subtype?

**Comment by oxinabox** [comment]
Yes.

**Comment by simonschoelly** [comment]
Can be closed then, I guess.
