### ISSUE TITLE
Incorrect type inference with generator constructor

### ISSUE THREAD

**Issue by juliohm** [JuliaCollections/OrderedCollections.jl#30]
Consider the MWE:

```Julia
using OrderedCollections

julia> d = OrderedDict(:a=>1, :b=>2)
julia> OrderedDict(k=>v for (k,v) in d)
OrderedDict{Any,Any} with 2 entries:
  :a => 1
  :b => 2
```

**Comment by oxinabox** [comment]
The way this works in `Base` is super gross, but we should use it.
IIRC it's `Base.@default_eltype`
Which has a special hack for generators

**Comment by juliohm** [comment]
Similar issue is now affecting the array-based constructor:

```Julia
julia> vars = OrderedDict([:a => Float64, :n => String])
OrderedDict{Symbol,DataType} with 2 entries:
  :a => Float64
  :n => String
julia> d1 = Dict([var => Vector{V}() for (var, V) in vars])
Dict{Symbol,Array{T,1} where T} with 2 entries:
  :a => Float64[]
  :n => String[]
julia> d2 = OrderedDict([var => Vector{V}() for (var, V) in vars])
OrderedDict{Any,Any} with 2 entries:
  :a => Float64[]
  :n => String[]
```

I am hacking my way out, but this OrderedDict constructors really deserve more love.

**Comment by timholy** [comment]
Care to give it a stab, @juliohm?

**Comment by juliohm** [comment]
Will try to checkout the code today @timholy and see what I can do. Reading the source quickly I couldn't spot the issue. I need to solve it anyways for some current research. This is actually a blocker for me.

**Comment by timholy** [comment]
So you're motivated then! Good :smile:

**Comment by juliohm** [comment]
I wonder if this is expected behaviour of list comprehensions:

```Julia
julia> v = [:a=>Float64, :n=>String]
2-element Array{Pair{Symbol,DataType},1}:
 :a => Float64
 :n => String 

julia> a = [s=>Vector{T}() for (s, T) in v]
2-element Array{Pair{Symbol,B} where B,1}:
 :a => Float64[]
 :n => String[] 

julia> eltype(a)
Pair{Symbol,B} where B
```

Shouldn't the eltype by `Pair{Symbol,Array{T,1} where {T}}` instead of the generic `B`?

**Comment by juliohm** [comment]
In any case, I can't understand why `eltype(a) <: Pair{Symbol,B} where B` and still the dispatch chooses the third option from the list below:

```Julia
dict_with_eltype(kv, ::Type{Tuple{K,V}}) where {K,V} = OrderedDict{K,V}(kv)
dict_with_eltype(kv, ::Type{Pair{K,V}}) where {K,V} = OrderedDict{K,V}(kv)
dict_with_eltype(kv, t) = OrderedDict{Any,Any}(kv)
```

Shouldn't it call the second option?

**Comment by juliohm** [comment]
I couldn't figure out yet how to fix the issue. Appreciate if someone familiar with the code can tackle it.

**Comment by eulerkochy** [comment]
Surely, I will take a look, maybe later tonight.

**Comment by eulerkochy** [comment]
ping: @juliohm take a look at #40 , and do comment if that satisfies your requirement.
