### ISSUE TITLE
Is OrderedDict maybe broken?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaCollections/OrderedCollections.jl#58]
I assumed it worked, when I but it in Base, I get error:

https://github.com/JuliaLang/julia/pull/37804#issuecomment-701427549

do you know if the code is correct and even better, either way how to fix in Base?

**Comment by fingolfin** [comment]
Thank you for your report. However I couldn't easily figure out from your linked comment what exactly you think may be erroneous.

If you still think there is a potential error, please open a new self-contained issue which contains the Julia input, what the output is, and why you believe this might be incorrect (and perhaps also what you would have expected instead).
