### ISSUE TITLE
OrderedDict missing `last`

### ISSUE THREAD

**Issue by jmigual** [JuliaCollections/OrderedCollections.jl#91]
OrderedDict provides a `first` method but does not provide a `last` method:

```julia
julia> a = OrderedDict(1 => "a", 2 => "b")
OrderedDict{Int64, String} with 2 entries:
  1 => "a"
  2 => "b"

julia> first(a)
1 => "a"

julia> last(a)
ERROR: MethodError: no method matching lastindex(::OrderedDict{Int64, String})
Closest candidates are:
  lastindex(::Any, ::Any) at ~\scoop\apps\julia\current\share\julia\base\abstractarray.jl:373
  lastindex(::Union{SortedDict, SortedMultiDict, SortedSet}) at ~\.julia\packages\DataStructures\izXYB\src\tokens2.jl:19
  lastindex(::Number) at ~\scoop\apps\julia\current\share\julia\base\number.jl:90
  ...
Stacktrace:
 [1] last(a::OrderedDict{Int64, String})
   @ Base .\abstractarray.jl:473
 [2] top-level scope
   @ REPL[26]:1

```

**Comment by oxinabox** [comment]
I have moved the issue.

The reason it doesn't need to implement `first` is because it implements `iterate` anything that implements `iterate` gets `first` for free as it can be define efficiently as just iterating once -- there is a fallback definition.
This is not the case for last.

I believe for OrderedDict there is a efficient and sensible way to define last.
So a PR can and should be made here to add it

**Comment by pri1311** [comment]
I tried working on this, but for some reason, the changes don't reflect. Not just my changes, but the previous commit adding `popfirst` also doesn't work on my PC. 
<img width="431" alt="Screenshot 2022-09-25 at 1 25 01 PM" src="https://user-images.githubusercontent.com/64613009/192133906-ccae015d-d083-4c87-bf04-2fd89ccb042a.png">

Any idea what I'm doing wrong?
Also, this is what I get after installing it again after making changes:
<img width="574" alt="Screenshot 2022-09-25 at 1 27 57 PM" src="https://user-images.githubusercontent.com/64613009/192133939-4dbdf3f6-4942-4737-a8d1-6633c4ed9502.png">

**Comment by StephenVavasis** [comment]
Is it possible you are forgetting to type `using OrderedCollections` when you restart the REPL?  Also, please note the "revise" workflow:

https://timholy.github.io/Revise.jl/stable/

which is popular for package developers.
