### ISSUE TITLE
last for OrderedDict/KeyIterator/ValueIterator

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/OrderedCollections.jl#99]
`first` works on all of these, but `last` doesn't
```julia

julia> dd =  OrderedDict(1=>2, 3=>4)
OrderedDict{Int64, Int64} with 2 entries:
  1 => 2
  3 => 4

julia> first(dd)
1 => 2

julia> last(dd)
ERROR: MethodError: no method matching lastindex(::OrderedDict{Int64, Int64})
...
```

But you can get them via:
```julia
julia> last(dd.keys)
3

julia> last(dd.vals)
4
```

But that is going in to the internals.

This should be a nice easy PR.
Just need to dispatch on  `Base.ValueIterator{OrderedDict{<:Any, <:Any}}` (similar for the `KeysIterator`) and look at the backing dict, and then look at it's `dict.vals`  (similarly `dict.keys`)

**Comment by pri1311** [comment]
Surprising! I have previously added a PR for the same - https://github.com/JuliaCollections/OrderedCollections.jl/pull/94 also works locally for me
<img width="575" alt="Screenshot 2023-08-05 at 12 53 52 AM" src="https://github.com/JuliaCollections/OrderedCollections.jl/assets/64613009/e32ae8b0-12ad-4b95-b420-dfb37c1a46a6">
